[package]
name = "izilogpds"
version = "0.1.0"
authors = ["Ivan Izaguirre <ivanizag@gmail.com>"]
edition = "2018"

[dependencies]
iz80 = "^0.3.4"
#iz80 = {path = "../iz80"}
clap = "^2"

[target.'cfg(unix)'.dependencies]
termios = "^0.3"

